// Generated by sim/knots_sim/codegen.py from sim/knots_sim/models/vessel.py. Do not edit: change the model
// in Python and run `uv run python -m knots_sim.export`.
/* eslint-disable */

export const STATES = ["x", "A", "m", "n", "my"] as const;
export const INPUTS = ["uS", "Pext"] as const;
export interface VesselParams {
  r100: number;
  Tmax: number;
  xopt: number;
  P: number;
  beta: number;
  width: number;
  wall: number;
  xc: number;
  tau_x: number;
  tau_up: number;
  tau_down: number;
  tau_debt: number;
  tau_nerve: number;
  collateral: number;
  myogenic: number;
  tau_myogenic: number;
  xrest: number;
}

/** d/dt of the state [x, A, m, n, my] given inputs [uS, Pext]; written into `out`. */
export function rhs(y: ArrayLike<number>, u: ArrayLike<number>, p: VesselParams, out: number[]): void {
  const x = y[0], A = y[1], m = y[2], n = y[3], my = y[4];
  const uS = u[0], Pext = u[1];
  const { r100, Tmax, xopt, P, beta, width, wall, xc, tau_x, tau_up, tau_down, tau_debt, tau_nerve, collateral, myogenic, tau_myogenic, xrest } = p;
  let d0: number, d1: number, d2: number, d3: number, d4: number;
  const c0 = -Math.exp(-beta);
  const c1 = (1/2)*wall;
  const c2 = 7.50063755419211e-5*(-A*Tmax*(1 - n)*Math.exp(-Math.pow(Math.sqrt(c1 + Math.pow(x, 2))/Math.sqrt(c1 + Math.pow(xopt, 2)) - 1, 2)/Math.pow(width, 2)) + r100*x*(133.322*P - 133.322*Pext) - 13332.2*r100*(c0 + Math.exp(beta*(x - 1)))/(c0 + 1))/r100;
  const c3 = -my*myogenic + 1;
  const c4 = -A + c3*uS;
  const c5 = Math.min(1, Math.pow(x, 4)/Math.pow(xrest, 4));
  const c6 = c5 - 1;
  const c7 = Math.min(1, Math.max(0, Pext/P));
  d0 = ((1 - Math.exp(-100.0*Math.max(0, x - xc)))*Math.min(0, c2) + Math.max(0, c2))/tau_x;
  d1 = ((A < c3*uS) ? (c4/tau_up) : (c4/tau_down));
  d2 = (c6*collateral*(1 - c7) - c6 - m)/tau_debt;
  d3 = (c5*m - n)/tau_nerve;
  d4 = (c7 - my)/tau_myogenic;
  out[0] = d0; out[1] = d1; out[2] = d2; out[3] = d3; out[4] = d4;
}

/** The effective tone A·(1 − n) that holds the vessel at radius x (the switch's equilibrium curve). */
export function aeq(x: number, Pext: number, p: VesselParams): number {
  const { r100, Tmax, xopt, P, beta, width, wall } = p;
  let r: number;
  const c0 = (1/2)*wall;
  const c1 = -Math.exp(-beta);
  r = (r100*x*(133.322*P - 133.322*Pext) - 13332.2*r100*(c1 + Math.exp(beta*(x - 1)))/(c1 + 1))*Math.exp(Math.pow(Math.sqrt(c0 + Math.pow(x, 2))/Math.sqrt(c0 + Math.pow(xopt, 2)) - 1, 2)/Math.pow(width, 2))/Tmax;
  return r;
}
