"""Write a model's equations out as TypeScript for the site, from the same SymPy expressions Python runs.

    uv run python -m knots_sim.codegen     # writes src/sim/models/vessel.ts
"""

from __future__ import annotations

from pathlib import Path

import sympy as sp
from sympy.printing.jscode import JavascriptCodePrinter

from .models import vessel

OUT = Path(__file__).resolve().parents[2] / "src" / "sim" / "models"


class _Printer(JavascriptCodePrinter):
    """JavaScript, with Piecewise as nested ternaries and booleans as comparisons."""

    def _print_Piecewise(self, expr):
        parts = []
        for e, c in expr.args[:-1]:
            parts.append(f"({self._print(c)}) ? ({self._print(e)}) : ")
        return "(" + "".join(parts) + f"({self._print(expr.args[-1][0])}))"


def _js(e: sp.Expr) -> str:
    return _Printer({"strict": False}).doprint(e)


def _block(exprs: list[sp.Expr], names: list[str], indent: str = "  ") -> list[str]:
    """Common subexpressions as consts, then one assignment per output."""
    subs, reduced = sp.cse(exprs, symbols=sp.numbered_symbols("c"))
    lines = [f"{indent}const {s} = {_js(v)};" for s, v in subs]
    lines += [f"{indent}{n} = {_js(v)};" for n, v in zip(names, reduced)]
    return lines


def _uses(exprs: list[sp.Expr], names: tuple[str, ...]) -> list[str]:
    free = {str(s) for e in exprs for s in e.free_symbols}
    return [n for n in names if n in free]


def vessel_ts() -> str:
    L = vessel.laws()
    st, ins, ps = vessel.STATES, vessel.INPUTS, vessel.PARAMS
    rhs_ps = _uses(list(L["rhs"]), ps)
    aeq_ps = _uses([L["Aeq"]], ps)
    head = [
        "// Generated by sim/knots_sim/codegen.py from sim/knots_sim/models/vessel.py. Do not edit: change the model",
        "// in Python and run `uv run python -m knots_sim.export`.",
        "/* eslint-disable */",
        "",
        f"export const STATES = {list(st)!r} as const;".replace("'", '"'),
        f"export const INPUTS = {list(ins)!r} as const;".replace("'", '"'),
        "export interface VesselParams {",
        *[f"  {k}: number;" for k in ps],
        "}",
        "",
        "/** d/dt of the state [x, A, m, n, my] given inputs [uS, Pext]; written into `out`. */",
        "export function rhs(y: ArrayLike<number>, u: ArrayLike<number>, p: VesselParams, out: number[]): void {",
        f"  const {', '.join(st)} = y[0], {', '.join(f'{s} = y[{i}]' for i, s in enumerate(st) if i)};".replace(
            f"{', '.join(st)} = y[0]", f"{st[0]} = y[0]"),
        f"  const {ins[0]} = u[0], {ins[1]} = u[1];",
        f"  const {{ {', '.join(rhs_ps)} }} = p;",
        "  let d0: number, d1: number, d2: number, d3: number, d4: number;",
        *_block(list(L["rhs"]), ["d0", "d1", "d2", "d3", "d4"]),
        "  out[0] = d0; out[1] = d1; out[2] = d2; out[3] = d3; out[4] = d4;",
        "}",
        "",
        "/** The effective tone A·(1 − n) that holds the vessel at radius x (the switch's equilibrium curve). */",
        "export function aeq(x: number, Pext: number, p: VesselParams): number {",
        f"  const {{ {', '.join(aeq_ps)} }} = p;",
        "  let r: number;",
        *_block([L["Aeq"]], ["r"]),
        "  return r;",
        "}",
        "",
    ]
    return "\n".join(head)


def write() -> Path:
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / "vessel.ts"
    path.write_text(vessel_ts())
    return path


if __name__ == "__main__":
    print(write())
