"""The findings note, written from a run's numbers so the prose can never drift from the results."""

from __future__ import annotations

from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "findings" / "001-can-a-perforator-hold.md"


def pct(x: float) -> str:
    return f"{100 * x:.0f}%"


def write_findings(d: dict) -> Path:
    s, v, r, c = d["switch"], d["validation"], d["robustness"], d["checks"]
    guessed = [p for p in d["params"]["vessel"] if p["confidence"] == "guessed"]
    guesses = ", ".join(p["label"] for p in guessed)
    q = r["quantiles"]
    sob = r["sobol"]["to_hold"]
    top = sorted(sob.items(), key=lambda kv: -kv[1]["ST"])[:3]
    names = {"width": "how much force the muscle keeps when the vessel is nearly shut (the width of its length–tension curve)",
             "wall": "the thickness of the wall", "xc": "how far the lumen closes", "r100": "the vessel's size",
             "P": "the pressure inside it", "Tmax": "the wall's maximal active tension", "beta": "the stiffness of the relaxed wall",
             "xopt": "the stretch at which the muscle is strongest", "porh_rise": "the measured size of reactive hyperaemia",
             "gasp_drop": "the measured size of the gasp reflex"}
    decide = "; ".join(f"{names[k]} (total Sobol index {min(v_['ST'], 1):.2f})" for k, v_ in top)
    sc = {k: x["summary"] for k, x in d["scenarios"].items()}

    def opened(name):
        ev = [e for e in sc[name]["events"] if e["to"] == "open"]
        return ev[0]["t"] if ev else None

    eased = opened("stress_eases")
    pressed = opened("press_and_release")
    relax = opened("relaxing_breath_at_threshold")
    col, cool = c["collar"], c["cooling"]
    run = d["run"]
    text = f"""# Can a perforator hold a knot? First findings

*Generated by `uv run python -m knots_sim.export` on {run['date']} (inputs {run['inputs']}: a hash of the model's code and parameter tables).
Every number below comes from that run; every parameter, with its source and the line it comes from, is in
`sim/params/`; the model is `sim/knots_sim/models/vessel.py`. The site shows the same results at /simulation/.*

## In brief

If a knot is a perforator held stuck, something has to hold it, and it has to let go within seconds. Four checks,
each made with published measurements:

1. **The vessel can hold itself.** A small artery with smooth muscle in its wall has two stable states, open and
   shut, over a band of tone (Burton 1951). With measured wall strength, pressure and reflex timings, the band runs
   from {s['Aopen']:.2f} to {s['Afold']:.2f} of maximal tone, just above resting tone ({s['urest']:.2f}). An open
   vessel snaps shut when tone passes {s['Afold']:.2f}; once shut, it stays shut until tone falls below
   {s['Aopen']:.2f}. That is *held until released*. Across {r['samples']:,} plausible parameter sets, a small artery
   is such a switch in {pct(r['share_bistable'])} of them.
2. **Hyaluronan cannot hold it.** A liquid resists motion, not position: at rest its drag is zero. At its most
   viscous (healthy synovial fluid, 175 Pa·s, in a collar 20 µm thin, around a vessel opening in a second) the drag
   reaches {col['drag_Pa']:.0f} Pa, {col['pressure_over_drag']:.0f} times weaker than the {round(col['pressure_Pa'], -2):,.0f} Pa
   holding the vessel open. Fascia holds {col['synovial_over_fascia_min']:.0f}–{col['synovial_over_fascia_max']:.0f}
   times less hyaluronan than that fluid, and without protein hyaluronan does not gel.
3. **Cooling cannot release it within a breath.** When a vessel opens, the patch of skin it feeds warms with a time
   constant of at least {cool['tau_s_at_max_flow']:.0f} s, even at the body's maximal skin blood flow, and about
   {cool['tau_s_at_tenth_flow'] / 60:.0f} minutes at a tenth of it. Reports of release within a breath need
   something faster than heat.
4. **The latch does not remember; it economises.** Smooth muscle can hold force with less calcium and ATP (the
   latch), but relaxation follows the fall of calcium, not latch-bridge detachment (Rembold 1991). A latch lets a
   held vessel stay held cheaply while the drive lasts; the memory must be elsewhere, and in the vessel switch it is
   the switch itself.

## 1. The vessel switch

**The balance.** The pressure inside a vessel pushes its wall out with a force per unit length of P·r; the wall
pulls in with passive tension, and with active tension that depends on how stretched its muscle is (strongest near
0.9 of the relaxed circumference at 100 mmHg; El Assar 2022). Solving the balance for the tone that holds each
radius gives a curve that rises to a fold as the vessel narrows and falls again toward the shut lumen. Tone above
the fold has no open balance: the vessel snaps shut. A shut vessel reopens only when the pressure force at its
closed lumen beats the tension the muscle still holds there.

**Calibrated to measurements.** Resting tone is set so that relaxing fully raises flow by the measured reactive
hyperaemia (+187%; Alexandrou 2021). The gasp's size is set so that it cuts flow by the measured 65% (Lau 1995);
how slowly nerve-driven tone fades is fitted to the gasp's recovery (about 34 s; Mayrovitz 2026); how fast the
sensory nerves act is fitted to the timing of reactive hyperaemia (11 s). One timing is left unfitted, and so is a
test: after a gasp the model's flow is lowest at {v['gasp']['at_s']:.1f} s, against a measured 4.6–5.2 s, about
{v['gasp']['at_s'] - 5.2:.1f} s late. After a 5-minute occlusion its flush reaches +{pct(v['flush']['rise'])} (measured
187 ± 61%), short of the full relaxation that sets resting tone.

**What the switch does.**

| Trial | What happens |
|---|---|
| A deep gasp at rest | flow dips and recovers; the vessel never shuts |
| A deep gasp with tone two-thirds up the band | tone passes the fold for a few seconds, but near a fold everything slows, and the vessel stays open |
| A surge of stress past the fold | the vessel shuts, and stays shut when stress falls back but stays raised: a knot, with an oxygen debt of {sc['knot_forms']['peak_debt']:.2f} that its sensory nerves feel |
| Stress eases | it reopens {eased - 110:.0f} s later, with a flush to {sc['stress_eases']['peak_flow']:.2f}× resting flow |
| A 40 s press, then release | it reopens {pressed - 150:.1f} s after the pressure lifts, with a flush to {sc['press_and_release']['peak_flow']:.2f}× and the brightest spark ({sc['press_and_release']['peak_spark']:.2f}, against {sc['stress_eases']['peak_spark']:.2f} when stress eases): the press ran up a debt, and returning blood repays it through the nerves |
| Even breathing, knot at the threshold | it holds: tone rises in about a second and fades over {d['params']['values']['tau_down']:.0f} s, so an even swing raises average tone |
| Relaxing breaths (the out-breath lowers drive; the in-breath does not raise it) | a knot at the threshold lets go after {relax - 40:.0f} s, about {(relax - 40) / 10:.0f} breaths |

**How robust.** Sampling every uncertain parameter across its range ({r['samples']:,} sets, Sobol design): a switch
exists in {pct(r['share_bistable'])}; a shut vessel stays shut even at resting tone in
{pct(r['share_holds_at_rest'])}; a single gasp shuts a relaxed vessel in only {pct(r['share_gasp_shuts_at_rest'])}.
The band runs from {q['Aopen'][1]:.2f} to {q['Afold'][1]:.2f} of maximal tone at the median (5–95%:
{q['Aopen'][0]:.2f}–{q['Aopen'][2]:.2f} and {q['Afold'][0]:.2f}–{q['Afold'][2]:.2f}). Whether a knot can hold at rest
is decided by {decide}. These are guesses today, and each can be measured in a myograph.

## What it predicts

- **A flush at release.** A perforator that lets go carries up to {sc['press_and_release']['peak_flow']:.1f}× its
  resting flow within seconds. Laser speckle imaging over the spot would see it; a theory with nothing held in the
  tissue predicts no local flush.
- **Pressure, then release, lets go faster and brighter than calm alone** ({pressed - 150:.1f} s against
  {eased - 110:.0f} s; spark {sc['press_and_release']['peak_spark']:.2f} against {sc['stress_eases']['peak_spark']:.2f}).
- **Slowing before a switch.** Near the fold, the vessel's response to small changes in tone slows; flow should flicker
  more slowly just before a knot forms under rising stress.
- **Breath releases knots only if it is uneven.** An out-breath has to lower sympathetic drive to the skin more than
  the in-breath raises it; this can be measured with laser Doppler over hairy skin.

## Limits

- {len(guessed)} parameters are guesses, marked as such on the site: {guesses}. The robustness sampling covers the
  ranges of those that shape the switch.
- The reflex timings are from glabrous skin (fingers, hands); most knots are reported over hairy skin, where the
  gasp reflex may be weaker.
- One vessel alone: no tree, no neighbours changing state, no other theory yet run through the same trials.
- The simulation shows what a mechanism can do with measured numbers. It measures nothing, and it does not show
  that knots are perforators.
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    return OUT
