"""The findings note, written from a run's numbers so the prose can never drift from the results."""

from __future__ import annotations

from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "findings" / "001-can-a-perforator-hold.md"


def pct(x: float) -> str:
    return f"{100 * x:.0f}%"


def write_findings(d: dict) -> Path:
    s, v, r, c = d["switch"], d["validation"], d["robustness"], d["checks"]
    guessed = [p for p in d["params"]["vessel"] if p["confidence"] == "guessed"]
    guesses = ", ".join(p["label"] for p in guessed)
    q = r["quantiles"]
    sob = r["sobol"]["to_hold"]
    top = sorted(sob.items(), key=lambda kv: -kv[1]["ST"])[:3]
    names = {"width": "how much force the muscle keeps when the vessel is nearly shut (the width of its length–tension curve)",
             "wall": "the thickness of the wall", "xc": "how far the lumen closes", "r100": "the vessel's size",
             "P": "the pressure inside it", "Tmax": "the wall's maximal active tension", "beta": "the stiffness of the relaxed wall",
             "xopt": "the stretch at which the muscle is strongest", "porh_rise": "the measured size of reactive hyperaemia",
             "gasp_drop": "the measured size of the gasp reflex"}
    decide = "; ".join(f"{names[k]} (total Sobol index {min(v_['ST'], 1):.2f})" for k, v_ in top)
    sc = {k: x["summary"] for k, x in d["scenarios"].items()}

    def opened(name):
        ev = [e for e in sc[name]["events"] if e["to"] == "open"]
        return ev[0]["t"] if ev else None

    eased = opened("stress_eases")
    pressed = opened("press_and_release")
    relax = opened("relaxing_breath_at_threshold")
    pr, se = sc["press_and_release"], sc["stress_eases"]
    brighter = pr["peak_spark"] > se["peak_spark"]
    flow_after = lambda x: f"{x['flow_after_open']:.2f}× resting flow" if x["flow_after_open"] is not None else "no flow"
    col, cool = c["collar"], c["cooling"]
    walls = {row["media_to_lumen"]: row for row in d["wall_sensitivity"]}
    held = lambda row: f"{row['Aopen'] / row['urest']:.1f}×"
    closure = d["closure_sensitivity"]
    tight, loose = closure[0], max((row for row in closure if row["bistable"]), key=lambda row: row["xc"])
    run = d["run"]
    text = f"""# Can a perforator hold a knot? First findings

*Generated by `uv run python -m knots_sim.export` on {run['date']} (inputs {run['inputs']}: a hash of the model's code and parameter tables).
Every number below comes from that run; every parameter, with its source and the line it comes from, is in
`sim/params/`; the model is `sim/knots_sim/models/vessel.py`. The site shows the same results at /simulation/.*

## In brief

If a knot is a perforator held stuck, something has to hold it, and it has to let go within seconds. Four checks,
each made with published measurements:

1. **The vessel can hold itself.** A small artery with smooth muscle in its wall has two stable states, open and
   shut, over a band of tone (Burton 1951). With measured wall strength, pressure and reflex timings, the band runs
   from {s['Aopen']:.2f} to {s['Afold']:.2f} of maximal tone, {s['Aopen'] / s['urest']:.1f} times resting tone ({s['urest']:.2f}) at its
   lower edge: in healthy vessels a knot would need tone well above rest to stay held. An open
   vessel snaps shut when tone passes {s['Afold']:.2f}; once shut, it stays shut until tone falls below
   {s['Aopen']:.2f}. That is *held until released*. Across {r['samples']:,} plausible parameter sets, a small artery
   is such a switch in {pct(r['share_bistable'])} of them.
2. **Hyaluronan cannot hold it.** A liquid resists motion, not position: at rest its drag is zero. At its most
   viscous (healthy synovial fluid, 175 Pa·s, in a collar 20 µm thin, around a vessel opening in a second) the drag
   reaches {col['drag_Pa']:.0f} Pa, {col['pressure_over_drag']:.0f} times weaker than the {round(col['pressure_Pa'], -2):,.0f} Pa
   holding the vessel open. Fascia holds {col['synovial_over_fascia_min']:.0f}–{col['synovial_over_fascia_max']:.0f}
   times less hyaluronan than that fluid, and without protein hyaluronan does not gel.
3. **Cooling cannot release it within a breath.** When a vessel opens, the patch of skin it feeds warms with a time
   constant of at least {cool['tau_s_at_max_flow']:.0f} s, even at the body's maximal skin blood flow, and about
   {cool['tau_s_at_tenth_flow'] / 60:.0f} minutes at a tenth of it. Reports of release within a breath need
   something faster than heat.
4. **The latch does not remember; it economises.** Smooth muscle can hold force with less calcium and ATP (the
   latch), but relaxation follows the fall of calcium, not latch-bridge detachment (Rembold 1991). A latch lets a
   held vessel stay held cheaply while the drive lasts; the memory must be elsewhere, and in the vessel switch it is
   the switch itself.

## 1. The vessel switch

**The balance.** The pressure inside a vessel pushes its wall out with a force per unit length of P·r; the wall
pulls in with passive tension, and with active tension that depends on how stretched its muscle is (strongest near
0.9 of the relaxed circumference at 100 mmHg; El Assar 2022). Solving the balance for the tone that holds each
radius gives a curve that rises to a fold as the vessel narrows and falls again toward the shut lumen. Tone above
the fold has no open balance: the vessel snaps shut. A shut vessel reopens only when the pressure force at its
closed lumen beats the tension the muscle still holds there.

**Calibrated to measurements.** Resting tone is set so that relaxing fully raises flow by the measured reactive
hyperaemia (+187%; Alexandrou 2021). The gasp's size is set so that it cuts flow by the measured 65% (Lau 1995);
how slowly nerve-driven tone fades is fitted to the gasp's recovery (about 34 s; Mayrovitz 2026); how fast the
sensory nerves act is fitted to the timing of reactive hyperaemia (11 s). One timing is left unfitted, and so is a
test: after a gasp the model's flow is lowest at {v['gasp']['at_s']:.1f} s, against a measured 4.6–5.2 s, about
{v['gasp']['at_s'] - 5.2:.1f} s late. After a 5-minute occlusion its flush reaches +{pct(v['flush']['rise'])} (measured
187 ± 61%), short of the full relaxation that sets resting tone.

**What the switch does.**

| Trial | What happens |
|---|---|
| A deep gasp at rest | flow dips and recovers; the vessel never shuts |
| A deep gasp with tone two-thirds up the band | tone passes the fold for a few seconds, but near a fold everything slows, and the vessel stays open |
| A surge of stress past the fold | the vessel shuts, and stays shut when stress falls back but stays raised: a knot, with an oxygen debt of {sc['knot_forms']['peak_debt']:.2f} that its sensory nerves feel |
| Stress eases | it reopens {eased - 110:.0f} s later; within 30 s flow is back to {flow_after(se)} |
| A 40 s press, then release | it reopens {pressed - 150:.1f} s after the pressure lifts, from near nothing to {flow_after(pr)} within 30 s, while drive stays raised; the sensory burst is {pr['peak_spark']:.2f} (against {se['peak_spark']:.2f} when stress eases) |
| Even breathing, knot at the threshold | it holds: tone rises in about a second and fades over {d['params']['values']['tau_down']:.0f} s, so an even swing raises average tone |
| Relaxing breaths (the out-breath lowers drive; the in-breath does not raise it) | a knot at the threshold lets go after {relax - 40:.0f} s, about {(relax - 40) / 10:.0f} breaths |

**How robust.** Sampling every uncertain parameter across its range ({r['samples']:,} sets, Sobol design): a switch
exists in {pct(r['share_bistable'])}; a shut vessel stays shut even at resting tone in
{pct(r['share_holds_at_rest'])}; a single gasp shuts a relaxed vessel in only {pct(r['share_gasp_shuts_at_rest'])}.
The band runs from {q['Aopen'][1]:.2f} to {q['Afold'][1]:.2f} of maximal tone at the median (5–95%:
{q['Aopen'][0]:.2f}–{q['Aopen'][2]:.2f} and {q['Afold'][0]:.2f}–{q['Afold'][2]:.2f}). Whether a knot can hold at rest
is decided by {decide}. These are guesses today, and each can be measured in a myograph.

**What moves the hold.** The wall: with its media 5.2% of the lumen's diameter, as in normotensive people (Schiffrin
1995), a shut vessel needs {held(walls[0.052])} resting tone to stay shut; at 8%, as in untreated hypertension,
{held(walls[0.08])}. How tightly a shut lumen closes, a guess: closed to {tight['xc']:.2f} of the relaxed radius it needs
{held(tight)}; closed only to {loose['xc']:.2f}, {held(loose)}. The tighter it closes, the less the pressure inside has to
push on. A vessel that cannot close past its fold ({s['xfold']:.2f} of the relaxed radius) has no second state at
all: narrowed is not held.

## What it predicts

- **Blood returns at release.** A perforator that lets go carries flow again within seconds, from near nothing: back to
  {flow_after(se)} when stress eases, {flow_after(pr)} after a press while drive stays raised. Laser speckle imaging over
  the spot would see it; a theory with nothing held in the tissue predicts no local change.
- **Pressure, then release, lets go faster than calm alone** ({pressed - 150:.1f} s against {eased - 110:.0f} s){', and brighter' if brighter else ''}
  (the sensory burst {pr['peak_spark']:.2f} against {se['peak_spark']:.2f}).
- **Slowing before a switch.** Near the fold, the vessel's response to small changes in tone slows; flow should flicker
  more slowly just before a knot forms under rising stress.
- **Breath releases knots only if it is uneven.** An out-breath has to lower sympathetic drive to the skin more than
  the in-breath raises it; this can be measured with laser Doppler over hairy skin.

## Limits

- {len(guessed)} parameters are guesses, marked as such on the site: {guesses}. The robustness sampling covers the
  ranges of those that shape the switch.
- The reflex timings are from glabrous skin (fingers, hands); most knots are reported over hairy skin, where the
  gasp reflex may be weaker.
- One vessel alone: no tree, no neighbours changing state, no other theory yet run through the same trials.
- The simulation shows what a mechanism can do with measured numbers. It measures nothing, and it does not show
  that knots are perforators.
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    return OUT


OUT2 = Path(__file__).resolve().parents[1] / "findings" / "002-breath-and-trees.md"


def write_breath_and_trees(d: dict) -> Path:
    """Findings 002: the breath's two routes over knot depth, and the tree of a parent and its children."""
    b, t, v = d["breath"], d["tree"], d["validation"]["squeeze"]
    run = d["run"]
    depths = b["depths"]
    pc = lambda x: f"{100 * x:.0f}%"
    cells = lambda xs: " | ".join("holds" if x is None else f"{x:.0f} s" for x in xs)
    route = {"even": "drive, even (±)", "uneven": "drive, uneven (−)", "settling": "drive, settling (−)",
             "movement": "movement (share of a squeeze)"}
    table = "\n".join(f"| {route[r['route']]} {r['size']:g} | {cells(r['release_s'])} |" for r in b["rows"])
    need = lambda k: " | ".join("none" if x is None else pc(x) for x in b["least_movement"][k])
    ease = b["easing"]
    fitted = next(r for r in ease["rows"] if r["fitted"])
    fast = next(r for r in ease["rows"] if abs(r["tau_down"] - 3.0) < 1e-9)
    tr, sib, fig = t["robustness"], t["siblings"], t["figure"]
    fd = d["field"]
    fc = fd["conditions"]
    corr = lambda x: "n/a" if x is None else f"{x:.2f}"
    qd = t["queue"]
    queue = ", ".join(f"{u:.2f}: {k}" for u, k, pk in zip(qd["drive"], qd["remain"], qd["parent_knot"]) if pk)
    first = {e["vessel"]: e["t"] for e in fig["events"] if e["to"] == "shut"}
    opened = [e for e in fig["events"] if e["to"] == "open"]
    parent_open = next(e["t"] for e in opened if e["vessel"] == 0)
    with_it = [e for e in opened if e["vessel"] and e["t"] - parent_open < 5]
    last = max(opened, key=lambda e: e["t"])
    text = f"""# Breath and trees: two routes, and clusters. Findings 002

*Generated by `uv run python -m knots_sim.export` on {run['date']} (inputs {run['inputs']}). Every number comes from that
run. The model is `sim/knots_sim/models/vessel.py` (the movement route) and `sim/knots_sim/models/tree.py`; the trials
are `sim/knots_sim/breath.py`. The site shows the same results at /research/.*

## In brief

1. **The breath has two routes, and the model now carries both.** Through drive, as before. Through movement: a change of
   shape loosens the wall's force for a while, saturating, fitted to squeezed arteries (clifford2006): +{pc(v['one']['rise'])}
   after one 1 s squeeze (measured +{pc(v['one']['measured']['rise'])}), +{pc(v['long']['rise'])} after one of 5 s
   (+{pc(v['long']['measured']['rise'])}), +{pc(v['five']['rise'])} after five (+{pc(v['five']['measured']['rise'])}), peaking
   {v['five']['peak_s']:.1f}–{v['long']['peak_s']:.1f} s after release (measured {v['five']['measured']['peak_s']}–{v['long']['measured']['peak_s']} s).
   The wall answers changes of shape, not held shapes, so the loosening adds up over breaths.
2. **An even breath holds every knot; easy knots go first; the deepest hold.** Over {b['breaths']} slow breaths:

| route | {' | '.join(pc(x) for x in depths)} |
|---|{'---|' * len(depths)}
{table}

   (Columns: how far above its own reopening threshold the drive holding the knot sits, as a share of the band.)
3. **What would have to be true for movement to be the route**: the least deformation per breath, as a share of a squeeze
   that shuts the vessel:

| within | {' | '.join(pc(x) for x in depths)} |
|---|{'---|' * len(depths)}
| 3 breaths | {need('within_3')} |
| 10 breaths | {need('within_10')} |

4. **One breath or many turns on how fast the skin's small arteries ease when drive falls.** With the value fitted to the
   gasp's recovery ({fitted['tau_down']:.0f} s), an uneven breath (−{ease['swing']}) releases the easiest knot after
   {fitted['release_s'][0]:.0f} s; if they eased in 3 s, after {fast['release_s'][0]:.0f} s. Nobody has measured it over hairy skin.
5. **Broad or focused.** On a patch of {fd['n']} perforators, each with its own wall and more stress in some zones,
   {fc['calm']['knots']} knots form under strong regional stress. With no breath, {fc['calm']['freed']} poised at their
   thresholds drift open. When drive eases everywhere (broad), {fc['broad']['freed']} let go, scattered across the patch,
   in order of difficulty (correlation of depth and release time {corr(fc['broad']['depth_vs_time'])}). When the breath moves the tissue around one spot (focused), {fc['focused']['freed_near']}
   of the {fc['focused']['knots_near']} knots within a radius of the spot let go and {fc['focused']['freed_far']} of the
   {fc['focused']['knots_far']} elsewhere. Together, {fc['both']['freed_near']} of {fc['both']['knots_near']} at the spot and
   {fc['both']['freed_far']} of {fc['both']['knots_far']} elsewhere. (The zones, the patch and the spot are representative.)
6. **One knot upstream makes a cluster below it.** In the worked tree (a parent and four children with walls from 0.25 to
   0.35, as in hypertension, drive {fig['u_m']:.2f}), a local surge shuts the parent at {first[0]:.0f} s and all four children within {max(first.values()) - first[0]:.1f} s,
   as the pressure below the parent collapses. Released after a 40 s press, the parent reopens at {parent_open:.0f} s and
   {len(with_it)} children with it within 5 s; the last lets go at {last['t']:.0f} s, after drive falls to rest.
7. **Across {tr['samples']} plausible trees** (pressures, the parent's resistance, the children's walls and the drive
   sampled): when the parent held a knot, a cluster formed beneath it in {pc(tr['share_cluster'])} ({tr['mean_cluster']:.1f}
   of 4 children on average); releasing the parent freed most of its cluster within 5 s in {pc(tr['share_cascade'])}; at
   least one child stayed held in {pc(tr['share_queue'])}. In the worked tree, the higher the drive, the longer the queue
   (drive: children left held) {queue}.
8. **Siblings on one feed protect each other.** Each closure raises the pressure holding the others open: a surge of
   stress shut {sib['shut_by_surge']} of {sib['siblings']}, where alone, at the same pressure, {sib['shut_alone']} would. Clusters come
   from the tree's hierarchy.

## Limits

- The movement route is calibrated on rat muscle feed arteries squeezed shut, not on skin; how much a breath deforms the
  tissue at a knot is unmeasured, so it is swept.
- The tree's resistances and pressures are guesses, sampled across ranges; a real tree branches further.
- The author's observation that a parent's release frees its children (O13) was written down after these runs were
  shared: the match is found after the fact.
- These are what the mechanisms can do with measured numbers. They measure nothing.
"""
    OUT2.parent.mkdir(parents=True, exist_ok=True)
    OUT2.write_text(text)
    return OUT2


OUT3 = Path(__file__).resolve().parents[1] / "findings" / "003-how-a-knot-sets.md"


def write_adaptation(d: dict, a: dict) -> Path:
    """Findings 003: length adaptation, the variant in which a held knot comes to hold at rest."""
    run = d["run"]
    h, hy, rb, rm = a["healthy"], a["hypertensive"], a["robustness"], a["remodel"]
    hours = lambda rows, m: next(r["hours"] for r in rows if abs(r["mult"] - m) < 1e-9)
    first = lambda rows: next(r for r in rows if r["hours"] is not None)
    sets = ", ".join(f"{m:g}×: {hours(h['set_h'], m):.1f} h" for m in (3.5, 4.0, 5.0))
    fl = {f["held_h"]: f for f in a["flushes"]}
    old = max((f for f in a["flushes"] if f["holds_at_rest"]), key=lambda f: f["held_h"])
    set_first = min((f for f in a["flushes"] if f["holds_at_rest"]), key=lambda f: f["held_h"])
    young = [f for f in a["flushes"] if 0 < f["held_h"] and not f["holds_at_rest"]]
    st = a["stories"]
    q = rb["set_h"]
    text = f"""# How a knot sets: length adaptation. Findings 003

*Generated by `uv run python -m knots_sim.export` on {run['date']} (inputs {run['inputs']}). Every number comes from that
run. The variant is `sim/knots_sim/adapt.py`, on the vessel switch of `sim/knots_sim/models/vessel.py`; its parameters,
with sources and quoted lines, are in `sim/params/adapt.yaml`. The site shows the same results at /research/.*

## In brief

The vessel switch alone holds a knot only while tone stays {h['aopen_over_rest']:.1f} times rest (findings 001). But smooth
muscle held at a new length adapts to it: it regains the force it lost, as its optimal length moves toward the length it is
held at (syyong2008, pratusevich1995, bednarek2011). Arterioles held constricted for 4 hours no longer relax fully when the
drive is removed (martinezlemus2004, hill2003); held for days, they remodel inward, and only if their muscle is active
(bakker2002). In this variant the muscle's optimal length follows the length it is held at, a share {a['share']:.2f} of the
way (fitted to the 73% of lost force that pulmonary arterial muscle regained at 0.6 of its length), with a time constant of
{a['tau_h']:.0f} h at full activation (bracketed by the arterioles: 5 minutes leaves no trace, 4 hours does).

1. **A knot can set.** Held shut at {st['hold_mult']:g} times resting tone, a knot comes to hold at rest after
   {hours(h['set_h'], st['hold_mult']):.1f} h: it outlasts the stress that made it. Held for {st['hour']['held_h']:.0f} h it
   {'stays' if st['hour']['stays'] else 'lets go when stress ends'}; for {st['three']['held_h']:.0f} h it {'stays' if st['three']['stays'] else 'lets go'}. The stronger the hold, the sooner it sets
   ({sets}). With the walls of hypertension it can be held from {first(hy['set_h'])['mult']:g} times rest and sets in
   {first(hy['set_h'])['hours']:.1f} h there.
2. **A set knot holds below rest.** Fully adapted, a shut vessel stays shut down to {h['adapted_aopen_over_rest']:.2f} of
   resting tone ({hy['adapted_aopen_over_rest']:.2f} with hypertensive walls). Calm alone no longer frees it: it needs drive
   below rest, pressure, or movement.
3. **Old knots let go with a wave; young ones without.** Released (drive dipped for a minute, then at rest), a knot
   held {old['held_h']:g} h opens to {old['peak_flow']:.1f} times resting flow, one held {set_first['held_h']:g} h to
   {set_first['peak_flow']:.1f} times: its muscle, adapted to being shut, is weak at open lengths until it re-adapts. A knot
   released before it set reopens narrowed instead ({', '.join(f"{f['peak_flow']:.2f} of resting flow after {f['held_h']:g} h held" for f in young)}),
   as the lab's arterioles did after 4 hours (martinezlemus2004), and a brand-new one to rest ({fl[0.0]['peak_flow']:.2f}).
   How long the flush lasts turns on what the model gets wrong (6): in it, with drive held at rest, the old knot's flush
   lasts {old['flush_h']:.1f} h and then the vessel, adapting again, shuts once more. If a flush lasts more than a minute,
   the skin warms (at least 44 s; findings 001).
4. **Days make it structural.** Three days of tone narrow the relaxed lumen by {100 * rm['shrink']:.0f}% around the same wall
   (bakker2002). That alone brings the tone that holds a shut vessel from {rm['before']:.1f} to {rm['aopen_over_rest']:.1f}
   times rest; adapted as well, to {rm['adapted_aopen_over_rest']:.2f}.
5. **Across {rb['samples']} plausible settings** (the adaptation's time and share, and the switch's own ranges): a switch in
   {pct(rb['share_bistable'])}; of these, {pct(rb['share_sets'])} can set, and {pct(rb['share_sets_within'])} do within
   {rb['within_h']:g} h held at the tone midway up the band. Median time to set {q[1]:.1f} h (5–95%: {q[0]:.1f}–{q[2]:.0f} h).
6. **Open vessels do not creep shut in the lab, and the model's do: something is missing.** With drive held constant and
   adaptation the only slow process, sustained tone of {h['creep_h'][0]['mult']:g} times rest narrows an open vessel until it
   shuts in {h['creep_h'][0]['hours']:.0f} h (2 times rest: {hours(h['creep_h'], 2.0):.1f} h); rest itself stays stable. But
   arterioles held at {100 * a['lab']['diameter']:.0f}% of their diameter for 4 hours kept that diameter while their cells
   repositioned (martinezlemus2004), where the model's would have shut within {a['lab']['shuts_h']:.1f} h. In an open vessel,
   adaptation seems to make holding a diameter cheaper, not narrower: activation eases as the muscle adapts, or flow and
   metabolism push back (a model of small arteries needs all its adaptive loops to stay stable; vanbavel2014). So sustained
   stress making knots without a surge (O4) is not shown. A shut vessel has no flow and holds only by its muscle, so the
   results above do not lean on the missing loop, so long as the drive keeps the knot shut while it adapts.

## What it predicts

- **The four-hour closure test.** In a pressure myograph, shut a small artery with an agonist for 5 minutes, or for 4 hours,
  then lower the agonist to a resting level. Under this variant the first reopens and the second stays shut; released at
  last, the second opens past its resting diameter. Arterioles held constricted for 4 hours already relax incompletely and
  slowly (martinezlemus2004, hill2003): the test asks whether a vessel held fully shut stays shut at resting tone.
- **The flush grows with a knot's age.** Over a knot, the flush at release should be absent for a new knot and near the
  maximal hyperaemia for one held for hours: laser speckle imaging at release, against the knot's history.
- **Old knots are harder.** A set knot needs drive below rest, pressure or movement; a new one goes with calm.

## Limits

- Adaptation is measured in isolated arterioles and in femoral, pulmonary and airway muscle, never in a skin perforator. The
  share is fitted at 0.6 of the muscle's length; a shut vessel's muscle sits near a third, beyond any measurement. In whole
  airways held inflated or deflated for about 50 minutes, adaptation did not appear (ansell2015).
- The time constant is bracketed, not measured; the robustness sample runs it from 20 minutes to 4 hours.
- Drive is held fixed here: in life, regulation would rein in a flush sooner and resist a narrowing open vessel.
- The length–tension curve is taken as symmetric about its optimum; how an adapted muscle pulls when stretched past its new
  optimum sets the size of the flush.
- One observation bears on this variant and was known when it was added: a young knot comes and goes, an old one persists
  (O10). The match is found after the fact; the tests above are the blind ones.
- These are what the mechanism can do with measured numbers. They measure nothing.
"""
    OUT3.parent.mkdir(parents=True, exist_ok=True)
    OUT3.write_text(text)
    return OUT3


EXAM_OUT = OUT.parent / "004-the-exam.md"
FAIRNESS = """- *One rule for the stress unit.* 1 is a surge that forms knots, and the holding stress (0.4–0.7) keeps them. Each theory
  sets its one scale so that the typical place that can hold a knot, where stress is held most, sits in the middle of its
  window: the surge makes it a knot, the holding stress keeps it one and cannot make it one alone.
- *Local trials start after 30 broad breaths*, once the easy knots have gone, so that what a focused breath or a press lets
  go is its own.
- *Easy and hard knots are read from a population:* the patch's own knots under 30 broad breaths (O1.5).
- *Time to form.* The surge lasts 3 minutes and the count is taken after 30 minutes at a stress, since some theories' knots
  form over slow loops.
- *Minutes of slow breathing calm* (oneda2010, adler2019): every theory whose breath acts through drive gets that sustained
  fall as well as each breath's dip; zero is in its range.
- *Each press as its own literature has it:* the trigger point's pressure release is calibrated to its quoted 60–90 s.
- *Sparks within 10 s*, the exam's reading of "within seconds".
- *One hand for every theory:* pressed until the knot lets go and stays let go for 2 s under it (one back sooner never
  let go), for a minute at most; then it lifts and does not come back.
- *Slow breathing begins without a jump:* halfway up an in-breath, so the first out-breath begins 2 s in (exam v4).
- *Rough impressions are shown, not decisive:* parts that rest on the author's rough impressions are scored and left out of
  the joint pass (exam v4)."""


def _share(c) -> str:
    return c if isinstance(c, str) else f"{100 * c:.0f}%"


def write_exam(m: dict) -> Path:
    """Findings 004: every modelled theory through the exam (matrix.json)."""
    run, ex, parts, th = m["run"], m["exam"], m["parts"], m["theories"]
    n = m["trials"]["samples"]

    def best(t, pid):
        vals = [v["cells"][pid] for v in t["variants"] if not isinstance(v["cells"][pid], str)]
        return max(vals) if vals else None

    scored = [p for p in parts if any(best(t, p["id"]) is not None for t in th)]
    none_can = [p for p in scored if all((best(t, p["id"]) or 0) == 0 for t in th)]
    only = [(p, [t for t in th if (best(t, p["id"]) or 0) > 0]) for p in scored]
    only = [(p, who[0]) for p, who in only if len(who) == 1]
    joint = max(v["joint"] for t in th for v in t["variants"])
    who = "; ".join(f"{t['id']} {t['name']} ({', '.join(v['name'] for v in t['variants'])})" for t in th)
    lower = lambda s: s[0].lower() + s[1:]
    word = ['no', 'one', 'two', 'three', 'four', 'five', 'six', 'seven'][len(th)]
    rough = [p for p in parts if p.get('rough')]

    lines = [f"""# Every theory through the same exam. Findings 004

*Generated by `uv run python -m knots_sim.exam` (inputs {run['inputs']}{f", commit {run['commit']}" if run.get('commit') else ''}).
Every number comes from that run. The exam is `sim/observations/spec.yaml`, version {ex['version']} of {ex['updated']}
(SHA-256 {ex['sha256'][:12]}…); the harness is `sim/knots_sim/exam.py`; each theory's mapping onto the trials is written
out at the top of its file in `sim/knots_sim/theories/`, for its proponents to check. The site shows the same matrix at
/research/#exam.*

## In brief

{word.capitalize()} of the seven theories have sat the exam: {who}. Each part was scored in {n} settings sampled across the
theory's own plausible ranges; a cell is the share of settings in which the part holds. It says what each theory can do,
never which is true. Parts that rest on the author's rough impressions ({', '.join(p['id'] for p in rough)}) are scored
and shown, and left out of the joint pass (exam v4).
"""]
    lines.append(f"- **All at once.** The best joint pass, every scored part in one setting (rough impressions aside), is {_share(joint)}."
                 + (" No variant does everything the reports describe." if joint == 0 else ""))
    if none_can:
        lines.append(f"- **None of the {word} can yet:** " + "; ".join(f"{p['id']} {lower(p['says'])}" for p in none_can) + ".")
    if only:
        lines.append("- **Only one can:** " + "; ".join(
            f"{p['id']} {p['short']} ({t['name']}, in {round(best(t, p['id']) * n)} of {n} settings)" for p, t in only) + ".")
    counts = [(t, t["variants"][0]["count"]) for t in th]
    def many(t, c):
        if not c:
            return f"{t['name']}: no unit to count"
        none = f", and none at all in {_share(c['none'])} of settings" if c["none"] > 0 else ""
        mid = f"{c['median_any']:,}" if c["median_any"] is not None else "none"
        return f"{t['name']}: {mid} knots in a body where it holds any, of {c['units']:,.0f} units{none}"

    lines.append("- **How many.** " + "; ".join(many(t, c) for t, c in counts)
                 + ". Practitioners who count report hundreds of thousands.")

    lines.append("- **The hand (open, Q1).** Pressed, with a slow out-breath, a knot often lets go within seconds; the author could"
                 " not say whether under the hand or as it eases off, so the exam takes either (v2). The theories split on it: "
                 + "; ".join(f"{t['name']} lets {_share(t['variants'][0]['hand']['under'])} go under the hand and"
                             f" {_share(t['variants'][0]['hand']['lift'])} as it lifts" for t in th) + ".")

    felt = [t for t in th if all(v["cells"].get("O17.1") == 1 for v in t["variants"])]
    unclench = [t for t in th if all(v["cells"].get("O17.2") == 1 for v in t["variants"])]
    lines.append("- **What the hand feels (O17, rough).** A knot can be felt as a bump, from a grain to perhaps a penny across,"
                 " beneath the skin, and it goes as it lets go, like an unclenching (the author, 27 Sep 2026). Read from each"
                 " theory's own account of what a knot is, the same in every setting: a bump beneath the skin in "
                 + (", ".join(t["name"] for t in felt) or "none") + "; one that goes like an unclenching in "
                 + (", ".join(t["name"] for t in unclench) or "none") + ". Only a contraction in muscle makes both.")

    cols = [(t, v) for t in th for v in t["variants"]]
    lines.append("\n## The matrix\n")
    lines.append("| part | " + " | ".join(f"{t['id']} {v['name']}" for t, v in cols) + " |")
    lines.append("|---|" + "---:|" * len(cols))
    for p in parts:
        lines.append(f"| {p['id']} {p['says']} | " + " | ".join(_share(v["cells"][p["id"]]) for _, v in cols) + " |")
    lines.append("| **every part at once** | " + " | ".join(_share(v["joint"]) for _, v in cols) + " |")

    lines.append("\n## How many knots each would hold\n")
    lines.append("The share of the theory's units holding a knot after 30 minutes of held stress in the patch, times the units a"
                 " body has by its own sources: as if the whole body were held like the patch, so an upper figure.\n")
    lines.append("| theory | units in a body | knots (median) | where it holds any | 10–90% of settings | settings with none |")
    lines.append("|---|---:|---:|---:|---:|---:|")
    for t, c in counts:
        if c:
            any_ = f"{c['median_any']:,}" if c["median_any"] is not None else "none"
            lines.append(f"| {t['name']} | {c['units']:,.0f} | {c['median']:,} | {any_} | {c['lo']:,}–{c['hi']:,} |"
                         f" {_share(c['none'])} |")
        else:
            lines.append(f"| {t['name']} | none: {t['notes'].get('O15', 'no unit')} | | | | |")

    lines.append("\n## When a pressed knot lets go (Q1, open)\n")
    lines.append("A press held a minute with slow breaths, then lifted: the share of each model's knots (over its settings and"
                 " the knot depths) that let go under the hand, within 5 s of the lift, later, or not within 30 s. The reports"
                 " cannot say which happens; it is the cheapest observation that would tell the theories apart.\n")
    lines.append("| theory · variant | knots | under the hand | as it lifts | later | holds | median time under the hand |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|")
    for t, v in cols:
        h = v["hand"]
        when = "–" if h["under_s"] is None else f"{h['under_s']:.0f} s"
        lines.append(f"| {t['id']} {v['name']} | {h['knots']} | {_share(h['under'])} | {_share(h['lift'])} | {_share(h['later'])} |"
                     f" {_share(h['held'])} | {when} |")
    lines.append("\n## After a knot lets go: where one comes back (O8.2)\n")
    lines.append("The author (27 Sep 2026): after a release, \"a new knot appears in what seems like the same place\"; \"it could be"
                 " the same perforator\", or feel like \"a knot from somewhere else moved there\". In each theory's cluster trial"
                 " the worked knot is pressed until it lets go (a minute at most), the hand lifts, the slow breaths go on and the"
                 " holding stress stays. Over the settings in which the knot let go, the share in which, within 10 minutes, a"
                 " knot is held at its place again: the same unit (once it had been let go for 2 s: sooner is a flicker, not a"
                 " release); a unit beneath it (a vessel's children); or an immediate neighbour not held before it let go.\n")
    lines.append("| theory · variant | settings | the same unit | beneath | beside | none | median time to it |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|")
    for t, v in cols:
        b = v.get("back")
        if not b:
            continue
        when = "–" if b["median_s"] is None else f"{b['median_s']:.0f} s"
        lines.append(f"| {t['id']} {v['name']} | {b['settings']} | {_share(b['same'])} | {_share(b['beneath'])} |"
                     f" {_share(b['beside'])} | {_share(b['none'])} | {when} |")
    lines.append("\nThe routes differ by theory, and so does what an instrument would find. In the perforators a knot back \"beneath\""
                 " is a child vessel the parent's release leaves shut: it was there all along, felt once the parent no longer"
                 " masks it, so it is counted 10 s after the release (the soonest the trial looks). A trigger point's own"
                 " contracture can return once the press's lengthening fades, if the drive that made it goes on. In perception,"
                 " the place, or one beside it, is felt again as attention moves. Whether the knot back is the same unit is what"
                 " the reports cannot say; a Doppler probe (a deeper vessel), a needle EMG (the same endplate) or nothing in the"
                 " tissue at all would.")

    lines.append("\nThe exam's first version was scored with the hand still pressing (the harness's reading of O2, stricter than its"
                 " words), and no theory passed it (findings 004 at commit c4cd6f9); version 2 takes a hand that holds or one that"
                 " eases off halfway through the out-breath.")

    lines.append("\n## Each theory\n")
    for t in th:
        b = {p["id"]: best(t, p["id"]) for p in parts}
        silent = [p["id"] for p in parts if all(v["cells"][p["id"]] == "silent" for v in t["variants"])]
        not_run = [p["id"] for p in parts if all(v["cells"][p["id"]] == "not run" for v in t["variants"])]
        ready = [pid for pid, x in b.items() if x is not None and x >= 0.5]
        some = [pid for pid, x in b.items() if x is not None and 0 < x < 0.5]
        zero = [pid for pid, x in b.items() if x == 0]
        lines.append(f"### {t['id']} {t['name']}\n")
        lines.append("Variants: " + "; ".join(f"*{v['name']}*, {v['description']}" for v in t["variants"]) + ".\n")
        lines.append(f"- In at least half the settings (its best variant): {', '.join(ready) or 'none'}.")
        lines.append(f"- In some settings: {', '.join(some) or 'none'}.")
        lines.append(f"- In none of {n}: {', '.join(zero) or 'none'}.")
        lines.append(f"- Silent: {', '.join(silent) or 'none'}. Not run yet: {', '.join(not_run) or 'none'}.")
        for pid, note in t["notes"].items():
            lines.append(f"- {pid}: {note}")
        lines.append("")

    lines.append("## Corrections since the first run (26 Sep 2026)\n")
    lines.append("- *O8 (now O8.1) for the perforators never ran.* Its sibling test put the knot to be released on the thinnest wall, which"
                 " cannot hold one, so its zeros said nothing. Found on the author's question about migration (27 Sep 2026); the"
                 " knot is now the thickest-walled sibling, as in the parent test, and every trial with a precondition reports"
                 " in how many settings it ran (a test fails if one never does).")
    lines.append("- *Perception's cluster trials (O8, O13) never ran either.* Its worked knot was pressed until it let go, and a"
                 " press makes a knot felt more, so it never did. Every theory's knot is now worked for a minute (press,"
                 " attention, slow breaths) and then the hand lifts; the check that each trial ran caught it.")
    lines.append("- *O2.2 read the hand as still pressing*, stricter than the words; the author could not say which, and exam v2"
                 " takes either.")
    lines.append("- *The cluster trials' hand differed by theory.* The perforators' press ran its full minute whether or not the"
                 " knot had let go; the trigger point's and perception's hand lifted at the release but pressed again if the knot"
                 " came back, which made knots near their threshold flicker. Found building O8.2 (27 Sep 2026): in every theory"
                 " the knot is now pressed until it lets go, for a minute at most, and the hand does not come back.")
    lines.append("- *Slow breathing began with a jump.* The shared breath started at the bottom of an out-breath, a step from the"
                 " breathing before it that let some of the motor switch's easiest knots go at once, before any out-breath. Found"
                 " building the seventh theory (27 Sep 2026): slow breathing now begins halfway up an in-breath, the first"
                 " out-breath 2 s in, and every theory is rerun with it.")
    lines.append("- *A knot back under the hand within 2 s had been counted as let go.* In the cluster trials the hand lifted at"
                 " the first moment the knot let go; the motor switch's knot, silenced under the hand, could be back the moment"
                 " it lifted, a flicker counted as a release. Now the hand stays until the knot has been let go for 2 s under"
                 " it, for every theory (27 Sep 2026).")
    lines.append("- *A knot let go in the work's first step was not counted as held when it began.* The patch trials read what"
                 " was held at the start from the record just after the work's first step; a unit silenced at once by"
                 " attention or a hand was missed. Found taking the hand and attention apart (27 Sep 2026); the record just"
                 " before it is read now, for every theory.\n")
    tested = [(t, v, pid, share) for t in th for v in t["variants"] for pid, share in v.get("tested", {}).items()]
    if tested:
        lines.append("Trials that ran, per theory and variant: " + "; ".join(
            f"{t['id']} {v['name']} {pid} in {round((share or 0) * n)} of {n}" for t, v, pid, share in tested) + ".\n")

    lines.append("## How the trials were made fair\n")
    lines.append("Found by running the first three theories; each applies to every theory, the ones not yet built included, and"
                 " any later change reruns them all (sim/PLAN.md §5b).\n")
    lines.append(FAIRNESS)
    lines.append("""
## Limits

- A zero is none of {n} settings, not impossible; one setting is {one}. Where a zero is structural, the theory's notes say so.
- The trials read the words one way (the `readings` in the spec); another reading could move a cell, and would be a new,
  dated version of the exam.
- Each theory is one formalisation of its account, in its strongest form as `src/data/hypotheses.ts` states it, with variants
  where the equations are a choice. Its proponents may formalise it otherwise; the mapping is written out to be checked.
- The rough parts rest on the author's impressions, \"not definitive but to be considered\": shown, not in the joint pass.
- The vascular latch, densification and the nerve view are not modelled yet; mirroring (O9), stiffness (O5) and accumulation
  with age (O10.2) need the mechanics and body stages.
""".format(n=n, one=f"{100 / n:.0f}%"))
    EXAM_OUT.write_text("\n".join(lines))
    return EXAM_OUT
